### ISSUE TITLE
Session sending message timeout

### ISSUE THREAD

**Issue by babaev** [quickfixgo/quickfix#80]
Currently session sends queued messages only after receiving incoming message or sessionEvent. 
[https://github.com/quickfixgo/quickfix/blob/master/session.go#L527](url)
Is it possible to remove this timeout by firing something like "needSend" event or by changing toSend queue to channel logic?

**Comment by cbusbey** [comment]
Hi @babaev.  So originally this was queuing logic, but you could end up in a deadlock if on fromApp or fromAdmin the caller sends a message and blocks waiting for that message to be processed.  So that's why we have the queuing logic you see now.  

I think you are on to something with the "needSend" event and would be a great enhancement to prevent the delayed send as you have described.  This contribution would be very welcome.

**Comment by cbusbey** [comment]
Ref #84
